# Generated by Django 4.0.1 on 2022-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=100)),
                ('stars', models.CharField(max_length=30)),
                ('forks', models.CharField(max_length=20)),
                ('watching', models.CharField(max_length=30)),
                ('commit', models.CharField(max_length=30)),
                ('last_commit', models.CharField(max_length=400)),
                ('release', models.CharField(max_length=100)),
                ('last_release', models.CharField(max_length=500)),
            ],
        ),
    ]
