# Generated by Django 4.0.1 on 2022-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocketspiders', '0003_dataspider_delete_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataspider',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
